export const TID = {
  navHome: "nav-home",
  navAbout: "nav-about",
  navTeam: "nav-team",
  navServices: "nav-services",
  navProcess: "nav-process",
  navSuccess: "nav-success",
  navInsights: "nav-insights",
  navFaq: "nav-faq",
  navLocations: "nav-locations",
  navContact: "nav-contact",
  navCta: "nav-cta",
  mobileMenuToggle: "mobile-menu-toggle",
  heroCta: "hero-cta",
  heroSecondaryCta: "hero-secondary-cta",
  homeServiceCard: "home-service-card",
  contactForm: "contact-form",
  contactName: "contact-name",
  contactCompany: "contact-company",
  contactEmail: "contact-email",
  contactPhone: "contact-phone",
  contactMessage: "contact-message",
  contactSubmit: "contact-submit",
  insightCard: "insight-card",
  faqItem: "faq-item",
  langToggle: "lang-toggle",
};
